version: '3.3'

services:
  api:
    build: ./
    restart: always
    network_mode: host
    container_name: production-api-container
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./dist:/usr/src/app/dist
      - ./.volumes/logs:/root/.npm/_logs
