version: '3.3'

services:
  api:
    image: node:12
    working_dir: /usr/src/app
    container_name: api-container
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - ./.volumes/logs:/root/.npm/_logs
    environment:
      - DB_COMPOSE_HOST=postgres
      - TZ=America/Sao_Paulo
    command: bash -c "yarn && yarn dev"

  postgres:
    image: postgres:13
    container_name: postgres-container
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    volumes:
      - ./.volumes/database:/var/lib/postgresql/data
