const VERIFICATION_CODE_EXPIRATION_IN_MINUTES = Number(
  process.env.VERIFICATION_CODE_EXPIRATION_IN_MINUTES,
);
const VERIFICATION_CODE_MAX_ATTEMPTS = Number(
  process.env.VERIFICATION_CODE_MAX_ATTEMPTS,
);

export {
  VERIFICATION_CODE_EXPIRATION_IN_MINUTES,
  VERIFICATION_CODE_MAX_ATTEMPTS,
};
