version: '3'
services:

  database:
    image: postgres:13
    restart: unless-stopped
    container_name: example-api-database
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    volumes:
      - ./.volumes/database:/var/lib/postgresql/data
    networks:
      - generic-rest-api-network
    tty: true

  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.prod
    image: throyer/example-node-api:latest
    platform: linux/x86_64
    restart: unless-stopped
    container_name: example-node-api
    links:
      - database
    ports:
      - 8080:80
    depends_on:
      - database
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_EXPIRATION_IN_MILLISECONDS: ${TOKEN_EXPIRATION_IN_MILLISECONDS}
      REFRESH_TOKEN_EXPIRATION_IN_MILLISECONDS: ${REFRESH_TOKEN_EXPIRATION_IN_MILLISECONDS}

      VERIFICATION_CODE_EXPIRATION_IN_MILLISECONDS: ${VERIFICATION_CODE_EXPIRATION_IN_MILLISECONDS}
      VERIFICATION_CODE_MAX_ATTEMPTS: ${VERIFICATION_CODE_MAX_ATTEMPTS}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      SWAGGER_URL: ${SWAGGER_URL}

      MAX_REQUESTS_PER_MINUTE: ${MAX_REQUESTS_PER_MINUTE}
    networks:
      - generic-rest-api-network
    tty: true
    entrypoint: "dockerize -wait tcp://database:5432 -timeout 20s npm run start:prod"

networks:
  generic-rest-api-network:
    driver: bridge
